### ISSUE TITLE
你好，我npm install项目报错

### ISSUE THREAD

**Issue by JserJser** [uwang/weex-app#1]
$ npm install
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ETIMEDOUT: request to https://registry.npmjs.org/ansi-escapes failed, reason: connect ETIMEDOUT 104.16.22.35:443
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/js-beautify/-/js-beautify-1.10.0.tgz failed, reason: connect ETIMEDOUT 104.16.22.35:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-06-06T09_52_11_904Z-debug.log

**Comment by uwang** [comment]
网络问题。使用淘宝镜像源

```
npm install -g nrm --registry=https://registry.npm.taobao.org
npm use taobao
npm install
```

这个项目只是尝试 weex 的 demo，请查阅官方文档进行学习使用。
